# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: Generate version
        id: generate_version
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "version=$(node ./.github/workflows/js/get-version.js ${branch})" >> $GITHUB_OUTPUT
      - name: Print version
        run: echo "${{ steps.generate_version.outputs.version }}"
